### ISSUE TITLE
help sir

### ISSUE THREAD

**Issue by yanhua1** [aab12345/thelounge-windows#1]
Hello sir, I am using the new version 4.3.1. After the convenient installation a folder appeared on the desktop, after clicking on Private.bat. What is the reason that this command does not bring up the cmd window. My computer is window 10

**Comment by aab12345** [comment]
Hi, it should bring up the CMD window, can you edit the file and add PAUSE to the last line, save and run and let me know what comes up with then please?  Take a screenshot and upload it somewhere for me to view.  Thanks

**Comment by yanhua1** [comment]
[https://i.imgur.com/n2heKYj.jpg](url)
ok sir

**Comment by aab12345** [comment]
Sorry I don't understand that language.
