### ISSUE TITLE
windows cant find Xgit-installer.exe

### ISSUE THREAD

**Issue by Lillebror420** [aab12345/thelounge-windows#2]
Heyo 

Everytime i try and install, i get a prompt where is says it cant fint Xgit-installer.exe i have looked inside the bat file and everything seems right

**Comment by aab12345** [comment]
Hello,

You could run the xgit-installer.exe manually.  By default it extracts all the files to a folder inside %temp% directory.  Let me just double check the latest version see if there's something up.

**Comment by aab12345** [comment]
You did download this installer didn't you? Just asking.

https://github.com/aab12345/thelounge-windows/releases/tag/v4.3.1

**Comment by Lillebror420** [comment]
yeah i downloaded, that i have tried install xgit manually with the file in the installer but of some reason it isnt compatible with windows 64 bit

**Comment by aab12345** [comment]
Let me do some testing I may have bundled in the wrong xgit installer.

**Comment by aab12345** [comment]
Please try the new release uploaded to

https://github.com/aab12345/thelounge-windows/releases/tag/v4.3.1

I made sure it was 64 bit by updating the binary.

Thanks
