### ISSUE TITLE
Cannot load module 7z.dll

### ISSUE THREAD

**Issue by pythonkenyard** [aab12345/thelounge-windows#4]
Error in install step 3 for me.
Im unsure where or what i can do to avoid this?
I tried running as administrator also.
I have this issue in both 4.3.0 and 4.3.1

**Comment by aab12345** [comment]
Are you running 32 bit windows or 64bit windows? Step 3 is:
7z.exe x *.zip -oc:\Users\%username% -y > nul

You could extract the files manually from thelounge4.3.1.zip, stick the extracted folder into C:\Users\%username% then remove step 3 from .auto-software-install2.bat

The files get extracted to %temp% folder.

**Comment by aab12345** [comment]
The new version is just uploading now.  Can you please try it? (4.3.1)

https://github.com/aab12345/thelounge-windows/releases

**Comment by aab12345** [comment]
So it's system related then, what operating system you running?

**Comment by pythonkenyard** [comment]
was just editing my comment sorry

64-bit operating system, x64-based processor
windows 10 Enterprise (H2 21)

**Comment by pythonkenyard** [comment]
C:\Users\Default.DESKTOP-THDFIPA\Downloads\TLC4.3.1>7z.exe t 7z.exe
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
ERROR:
Can't load module: 7z.dll
--------------------------------------------------------------
C:\Users\Default.DESKTOP-THDFIPA\Downloads\TLC4.3.1>7z.exe l 7z.exe
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
ERROR:
Can't load module: 7z.dll

**Comment by aab12345** [comment]
Can you try and just install 7zip the application please from the 7zip website?

Get the 32 bit version and install it then run the installer again.

**Comment by pythonkenyard** [comment]
thats done it but my username has a "." in it so its failing on the next steps because its cutting the username at .

ERROR: Can not open output file : The system cannot find the path specified. : c:\Users\Default\thelounge\src\models\msg.js

username is default.desktop-abc

**Comment by aab12345** [comment]
Ah that's interesting, next step is there any chance you could create a new user on your pc? If it works then you will probably need to move over to a new profile ideally.

**Comment by pythonkenyard** [comment]
I edited the .auto-software-install2.bat
replaced %username% with my profile name and its working now (or its on step 4 of 6 without error)

interesting i have never run into this issue before. 
i just had some default created username when installing but probably have this some years now.

i dont know if there is an alternative to username e.g. %USERPROFILE%?

**Comment by aab12345** [comment]
I will check it out see if %userprofile% path works. Cheers

Glad it's working!

**Comment by pythonkenyard** [comment]
thanks for the 7zip. ive just been using winrar so never had need for it :)

**Comment by aab12345** [comment]
> thanks for the 7zip. ive just been using winrar so never had need for it :)

That seems to work! Updated the batch files with %UserProfile% and %ProgramFiles% variable.  Should fix it.

Would you mind testing this for me to see if the installer runs right the way through now?  Just uploading the new one so in around 3 mins it should be uploaded.  Thanks!

**Comment by aab12345** [comment]
I think this is resolved now, no real need to test further.  I've done some testing this end and appears to work.

Thumbs up, thanks for testing.
